# Generated by Django 4.1.4 on 2023-03-28 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Animals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('peso', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('altura', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('sobre', models.CharField(max_length=500)),
                ('image', models.ImageField(upload_to='')),
                ('categoria', models.ManyToManyField(related_name='animals', to='joq.categoria')),
            ],
        ),
    ]
